// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhvdprbO7Q9oUGn0viWg8DfI0Yop7N50',
    appId: '1:319680095871:web:fc452f9f6b6ad42fb1414a',
    messagingSenderId: '319680095871',
    projectId: 'cs-ia2',
    authDomain: 'cs-ia2.firebaseapp.com',
    storageBucket: 'cs-ia2.appspot.com',
    measurementId: 'G-2EC9S3L4QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDekaCdGsum2kHx8XFUBXu4c3SSda6p2sY',
    appId: '1:319680095871:android:1617f390003aa6e1b1414a',
    messagingSenderId: '319680095871',
    projectId: 'cs-ia2',
    storageBucket: 'cs-ia2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVefoCRsYlDzZiOse6DiD6VV9zXO4Q49o',
    appId: '1:319680095871:ios:f7a5717367a537cbb1414a',
    messagingSenderId: '319680095871',
    projectId: 'cs-ia2',
    storageBucket: 'cs-ia2.appspot.com',
    iosClientId: '319680095871-r3qm2d9gh5k9i638aqvn792aurmpkn2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVefoCRsYlDzZiOse6DiD6VV9zXO4Q49o',
    appId: '1:319680095871:ios:f7a5717367a537cbb1414a',
    messagingSenderId: '319680095871',
    projectId: 'cs-ia2',
    storageBucket: 'cs-ia2.appspot.com',
    iosClientId: '319680095871-r3qm2d9gh5k9i638aqvn792aurmpkn2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
